// SPDX-License-Identifier: MIT
// LSFG-VK — Vulkan Frame Generation Layer for Android ARM64
// layer/optical_flow.cpp — GPU optical flow engine

#include "optical_flow.h"
#include "layer.h"

// Embedded SPIR-V (generated by cmake/SpvToHeader.cmake at build time)
#include "optical_flow_pyramid_spv.h"
#include "optical_flow_warp_spv.h"
#include "optical_flow_blend_spv.h"
#include "motion_vectors_spv.h"
#include "ui_mask_spv.h"

#include <cstring>

// ─── Init ────────────────────────────────────────────────────────────────────
VkResult OpticalFlowEngine::Init(DeviceContext* ctx,
                                  uint32_t width, uint32_t height,
                                  VkFormat format)
{
    m_ctx    = ctx;
    m_width  = width;
    m_height = height;
    m_format = format;

    VK_CHECK(CreateSamplers());
    VK_CHECK(CreateDescriptorPool());
    VK_CHECK(CreatePyramidResources());
    VK_CHECK(CreatePipelines());

    LOGI("OpticalFlowEngine: init OK [%ux%u, %u pyramid levels]",
         width, height, PYRAMID_LEVELS);
    return VK_SUCCESS;
}

// ─── CreateSamplers ──────────────────────────────────────────────────────────
VkResult OpticalFlowEngine::CreateSamplers() {
    VkDevice dev = m_ctx->device;
    const DeviceDispatch& d = m_ctx->dispatch;

    VkSamplerCreateInfo sci = {};
    sci.sType        = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
    sci.magFilter    = VK_FILTER_LINEAR;
    sci.minFilter    = VK_FILTER_LINEAR;
    sci.mipmapMode   = VK_SAMPLER_MIPMAP_MODE_NEAREST;
    sci.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    sci.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    sci.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    VK_CHECK(d.CreateSampler(dev, &sci, nullptr, &m_linearSampler));

    sci.magFilter = VK_FILTER_NEAREST;
    sci.minFilter = VK_FILTER_NEAREST;
    VK_CHECK(d.CreateSampler(dev, &sci, nullptr, &m_nearestSampler));

    return VK_SUCCESS;
}

// ─── CreateDescriptorPool ────────────────────────────────────────────────────
VkResult OpticalFlowEngine::CreateDescriptorPool() {
    VkDevice dev = m_ctx->device;
    const DeviceDispatch& d = m_ctx->dispatch;

    // Generous pool: 5 pipelines × PYRAMID_LEVELS × 10 sets each
    std::vector<VkDescriptorPoolSize> sizes = {
        { VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 128 },
        { VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,           64 },
    };

    VkDescriptorPoolCreateInfo poolCI = {};
    poolCI.sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    poolCI.flags         = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
    poolCI.maxSets       = 64;
    poolCI.poolSizeCount = (uint32_t)sizes.size();
    poolCI.pPoolSizes    = sizes.data();
    VK_CHECK(d.CreateDescriptorPool(dev, &poolCI, nullptr, &m_descPool));

    return VK_SUCCESS;
}

// ─── AllocatePyramidLevel ────────────────────────────────────────────────────
VkResult OpticalFlowEngine::AllocatePyramidLevel(PyramidLevel& level,
                                                   uint32_t w, uint32_t h,
                                                   VkFormat fmt,
                                                   VkImageUsageFlags usage)
{
    VkDevice dev = m_ctx->device;
    const DeviceDispatch& d = m_ctx->dispatch;

    level.width  = w;
    level.height = h;

    VkImageCreateInfo imgCI = {};
    imgCI.sType         = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    imgCI.imageType     = VK_IMAGE_TYPE_2D;
    imgCI.format        = fmt;
    imgCI.extent        = { w, h, 1 };
    imgCI.mipLevels     = 1;
    imgCI.arrayLayers   = 1;
    imgCI.samples       = VK_SAMPLE_COUNT_1_BIT;
    imgCI.tiling        = VK_IMAGE_TILING_OPTIMAL;
    imgCI.usage         = usage;
    imgCI.sharingMode   = VK_SHARING_MODE_EXCLUSIVE;
    imgCI.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    VK_CHECK(d.CreateImage(dev, &imgCI, nullptr, &level.image));

    VkMemoryRequirements memReq;
    d.GetImageMemoryRequirements(dev, level.image, &memReq);
    uint32_t memType = FindMemoryType(m_ctx->memProps, memReq.memoryTypeBits,
                                      VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (memType == UINT32_MAX) return VK_ERROR_OUT_OF_DEVICE_MEMORY;
    VkMemoryAllocateInfo allocInfo = {};
    allocInfo.sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    allocInfo.allocationSize  = memReq.size;
    allocInfo.memoryTypeIndex = memType;
    VK_CHECK(d.AllocateMemory(dev, &allocInfo, nullptr, &level.memory));
    VK_CHECK(d.BindImageMemory(dev, level.image, level.memory, 0));

    VkImageViewCreateInfo viewCI = {};
    viewCI.sType      = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    viewCI.image      = level.image;
    viewCI.viewType   = VK_IMAGE_VIEW_TYPE_2D;
    viewCI.format     = fmt;
    viewCI.subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 };
    VK_CHECK(d.CreateImageView(dev, &viewCI, nullptr, &level.view));

    return VK_SUCCESS;
}

// ─── FreePyramidLevel ────────────────────────────────────────────────────────
void OpticalFlowEngine::FreePyramidLevel(PyramidLevel& level) {
    if (!m_ctx) return;
    VkDevice dev = m_ctx->device;
    const DeviceDispatch& d = m_ctx->dispatch;
    if (level.view)   d.DestroyImageView(dev, level.view, nullptr);
    if (level.image)  d.DestroyImage(dev, level.image, nullptr);
    if (level.memory) d.FreeMemory(dev, level.memory, nullptr);
    level = {};
}

// ─── CreatePyramidResources ──────────────────────────────────────────────────
VkResult OpticalFlowEngine::CreatePyramidResources() {
    // RGBA8 for colour pyramids; RG16F for motion vector pyramids
    constexpr VkImageUsageFlags colourUsage =
        VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
    constexpr VkImageUsageFlags mvUsage =
        VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
    constexpr VkImageUsageFlags maskUsage =
        VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;

    uint32_t w = m_width, h = m_height;
    for (uint32_t lvl = 0; lvl < PYRAMID_LEVELS; lvl++) {
        uint32_t lw = std::max(1u, w >> lvl);
        uint32_t lh = std::max(1u, h >> lvl);

        VK_CHECK(AllocatePyramidLevel(m_prevPyramid[lvl], lw, lh,
                                      VK_FORMAT_R8G8B8A8_UNORM, colourUsage));
        VK_CHECK(AllocatePyramidLevel(m_currPyramid[lvl], lw, lh,
                                      VK_FORMAT_R8G8B8A8_UNORM, colourUsage));
        VK_CHECK(AllocatePyramidLevel(m_mvPyramid[lvl], lw, lh,
                                      VK_FORMAT_R16G16_SFLOAT, mvUsage));
    }

    // UI mask (full resolution, R8_UNORM)
    VK_CHECK(AllocatePyramidLevel(
        *reinterpret_cast<PyramidLevel*>(&m_uiMaskImage),  // reuse struct trick
        m_width, m_height, VK_FORMAT_R8_UNORM, maskUsage));
    // Manual assignment since we're not using the struct trick properly:
    VkImageCreateInfo imgCI = {};
    imgCI.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    imgCI.imageType = VK_IMAGE_TYPE_2D;
    imgCI.format = VK_FORMAT_R8_UNORM;
    imgCI.extent = { m_width, m_height, 1 };
    imgCI.mipLevels = 1; imgCI.arrayLayers = 1;
    imgCI.samples = VK_SAMPLE_COUNT_1_BIT;
    imgCI.tiling  = VK_IMAGE_TILING_OPTIMAL;
    imgCI.usage   = maskUsage;
    imgCI.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    imgCI.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    VK_CHECK(m_ctx->dispatch.CreateImage(m_ctx->device, &imgCI, nullptr, &m_uiMaskImage));
    VkMemoryRequirements memReq;
    m_ctx->dispatch.GetImageMemoryRequirements(m_ctx->device, m_uiMaskImage, &memReq);
    uint32_t memType = FindMemoryType(m_ctx->memProps, memReq.memoryTypeBits,
                                      VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    VkMemoryAllocateInfo allocInfo = {};
    allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    allocInfo.allocationSize = memReq.size;
    allocInfo.memoryTypeIndex = memType;
    VK_CHECK(m_ctx->dispatch.AllocateMemory(m_ctx->device, &allocInfo, nullptr, &m_uiMaskMem));
    VK_CHECK(m_ctx->dispatch.BindImageMemory(m_ctx->device, m_uiMaskImage, m_uiMaskMem, 0));
    VkImageViewCreateInfo viewCI = {};
    viewCI.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    viewCI.image = m_uiMaskImage;
    viewCI.viewType = VK_IMAGE_VIEW_TYPE_2D;
    viewCI.format = VK_FORMAT_R8_UNORM;
    viewCI.subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 };
    VK_CHECK(m_ctx->dispatch.CreateImageView(m_ctx->device, &viewCI, nullptr, &m_uiMaskView));

    return VK_SUCCESS;
}

// ─── CreateComputePipeline ───────────────────────────────────────────────────
VkResult OpticalFlowEngine::CreateComputePipeline(
        const uint32_t*   spvCode,
        size_t            spvSize,
        VkDescriptorSetLayout setLayout,
        uint32_t          pushConstSize,
        VkPipelineLayout* outLayout,
        VkPipeline*       outPipeline)
{
    VkDevice dev = m_ctx->device;
    const DeviceDispatch& d = m_ctx->dispatch;

    // Shader module
    VkShaderModuleCreateInfo smCI = {};
    smCI.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    smCI.codeSize = spvSize;
    smCI.pCode    = spvCode;
    VkShaderModule shaderModule;
    VK_CHECK(d.CreateShaderModule(dev, &smCI, nullptr, &shaderModule));

    // Pipeline layout
    VkPushConstantRange pcRange = {};
    pcRange.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    pcRange.offset     = 0;
    pcRange.size       = pushConstSize;

    VkPipelineLayoutCreateInfo layoutCI = {};
    layoutCI.sType                  = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutCI.setLayoutCount         = 1;
    layoutCI.pSetLayouts            = &setLayout;
    layoutCI.pushConstantRangeCount = (pushConstSize > 0) ? 1 : 0;
    layoutCI.pPushConstantRanges    = (pushConstSize > 0) ? &pcRange : nullptr;
    VK_CHECK(d.CreatePipelineLayout(dev, &layoutCI, nullptr, outLayout));

    // Compute pipeline
    VkComputePipelineCreateInfo pipeCI = {};
    pipeCI.sType  = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    pipeCI.layout = *outLayout;
    pipeCI.stage.sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    pipeCI.stage.stage  = VK_SHADER_STAGE_COMPUTE_BIT;
    pipeCI.stage.module = shaderModule;
    pipeCI.stage.pName  = "main";
    VkResult result = d.CreateComputePipelines(
        dev, VK_NULL_HANDLE, 1, &pipeCI, nullptr, outPipeline);

    d.DestroyShaderModule(dev, shaderModule, nullptr);
    return result;
}

// ─── CreatePipelines ─────────────────────────────────────────────────────────
VkResult OpticalFlowEngine::CreatePipelines() {
    VkDevice dev = m_ctx->device;
    const DeviceDispatch& d = m_ctx->dispatch;

    // ── Helper to create a 2-binding descriptor set layout ───────────────────
    auto makeLayout = [&](VkDescriptorType typeA, VkDescriptorType typeB,
                          VkDescriptorSetLayout* out) -> VkResult {
        VkDescriptorSetLayoutBinding bindings[2] = {};
        bindings[0].binding         = 0;
        bindings[0].descriptorType  = typeA;
        bindings[0].descriptorCount = 1;
        bindings[0].stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;
        bindings[1].binding         = 1;
        bindings[1].descriptorType  = typeB;
        bindings[1].descriptorCount = 1;
        bindings[1].stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;

        VkDescriptorSetLayoutCreateInfo ci = {};
        ci.sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
        ci.bindingCount = 2;
        ci.pBindings    = bindings;
        return d.CreateDescriptorSetLayout(dev, &ci, nullptr, out);
    };

    // Pyramid: sampler(src) → storage(dst)
    VK_CHECK(makeLayout(VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
                        VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, &m_pyramidLayout));

    // Motion vectors: sampler(prevPyr) + sampler(currPyr) + storage(mv)
    {
        VkDescriptorSetLayoutBinding b[3] = {};
        for (int i = 0; i < 3; i++) {
            b[i].binding         = i;
            b[i].descriptorCount = 1;
            b[i].stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;
            b[i].descriptorType  = (i < 2)
                ? VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER
                : VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
        }
        VkDescriptorSetLayoutCreateInfo ci = {};
        ci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
        ci.bindingCount = 3; ci.pBindings = b;
        VK_CHECK(d.CreateDescriptorSetLayout(dev, &ci, nullptr, &m_mvLayout));
    }

    // Warp: sampler(prev) + sampler(curr) + sampler(mv) → storage(out)
    {
        VkDescriptorSetLayoutBinding b[4] = {};
        for (int i = 0; i < 4; i++) {
            b[i].binding = i; b[i].descriptorCount = 1;
            b[i].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
            b[i].descriptorType = (i < 3)
                ? VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER
                : VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
        }
        VkDescriptorSetLayoutCreateInfo ci = {};
        ci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
        ci.bindingCount = 4; ci.pBindings = b;
        VK_CHECK(d.CreateDescriptorSetLayout(dev, &ci, nullptr, &m_warpLayout));
    }

    // Blend: sampler(warpPrev) + sampler(warpCurr) + sampler(mask) → storage(out)
    VK_CHECK(makeLayout(VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
                        VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, &m_blendLayout));

    // Mask: sampler(curr) → storage(mask)
    VK_CHECK(makeLayout(VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
                        VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, &m_maskLayout));

    // ── Create pipelines ─────────────────────────────────────────────────────
    VK_CHECK(CreateComputePipeline(
        optical_flow_pyramid_spv, sizeof(optical_flow_pyramid_spv),
        m_pyramidLayout, sizeof(PyramidPushConst),
        &m_pyramidPipeLayout, &m_pyramidPipeline));

    VK_CHECK(CreateComputePipeline(
        motion_vectors_spv, sizeof(motion_vectors_spv),
        m_mvLayout, sizeof(MotionVectorPushConst),
        &m_mvPipeLayout, &m_mvPipeline));

    VK_CHECK(CreateComputePipeline(
        optical_flow_warp_spv, sizeof(optical_flow_warp_spv),
        m_warpLayout, sizeof(WarpPushConst),
        &m_warpPipeLayout, &m_warpPipeline));

    VK_CHECK(CreateComputePipeline(
        optical_flow_blend_spv, sizeof(optical_flow_blend_spv),
        m_blendLayout, sizeof(BlendPushConst),
        &m_blendPipeLayout, &m_blendPipeline));

    VK_CHECK(CreateComputePipeline(
        ui_mask_spv, sizeof(ui_mask_spv),
        m_maskLayout, sizeof(BlendPushConst),
        &m_maskPipeLayout, &m_maskPipeline));

    LOGI("OpticalFlowEngine: all %u pipelines created", 5u);
    return VK_SUCCESS;
}

// ─── ImageBarrier ────────────────────────────────────────────────────────────
void OpticalFlowEngine::ImageBarrier(
        VkCommandBuffer cmd,
        VkImage         image,
        VkImageLayout   oldLayout,
        VkImageLayout   newLayout,
        VkAccessFlags   srcAccess,
        VkAccessFlags   dstAccess,
        VkPipelineStageFlags srcStage,
        VkPipelineStageFlags dstStage)
{
    VkImageMemoryBarrier barrier = {};
    barrier.sType               = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    barrier.oldLayout           = oldLayout;
    barrier.newLayout           = newLayout;
    barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    barrier.image               = image;
    barrier.subresourceRange    = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 };
    barrier.srcAccessMask       = srcAccess;
    barrier.dstAccessMask       = dstAccess;
    m_ctx->dispatch.CmdPipelineBarrier(
        cmd, srcStage, dstStage, 0, 0, nullptr, 0, nullptr, 1, &barrier);
}

// ─── ComputeMotionVectors ────────────────────────────────────────────────────
void OpticalFlowEngine::ComputeMotionVectors(
        VkCommandBuffer cmd,
        VkImageView     prevFrame,
        VkImageView     currFrame,
        VkImage         mvImage,
        VkImageView     mvView,
        float           t)
{
    const DeviceDispatch& d = m_ctx->dispatch;

    // ── 1. Build pyramids ────────────────────────────────────────────────────
    // (prevFrame → m_prevPyramid, currFrame → m_currPyramid)
    // For brevity: dispatch pyramid compute passes level by level.
    for (uint32_t lvl = 0; lvl < PYRAMID_LEVELS; lvl++) {
        uint32_t sw = (lvl == 0) ? m_width  : m_prevPyramid[lvl-1].width;
        uint32_t sh = (lvl == 0) ? m_height : m_prevPyramid[lvl-1].height;
        uint32_t dw = m_prevPyramid[lvl].width;
        uint32_t dh = m_prevPyramid[lvl].height;

        // Transition pyramid outputs to GENERAL for writing
        ImageBarrier(cmd, m_prevPyramid[lvl].image,
                     VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL,
                     0, VK_ACCESS_SHADER_WRITE_BIT,
                     VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                     VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);
        ImageBarrier(cmd, m_currPyramid[lvl].image,
                     VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL,
                     0, VK_ACCESS_SHADER_WRITE_BIT,
                     VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                     VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);

        d.CmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_pyramidPipeline);

        // Pyramid push constants
        PyramidPushConst pc = { sw, sh, dw, dh };
        d.CmdPushConstants(cmd, m_pyramidPipeLayout,
                           VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(pc), &pc);

        // Dispatch (8×8 workgroups)
        uint32_t gx = (dw + 7) / 8;
        uint32_t gy = (dh + 7) / 8;
        d.CmdDispatch(cmd, gx, gy, 1);

        // Memory barrier between levels
        VkMemoryBarrier mb = { VK_STRUCTURE_TYPE_MEMORY_BARRIER };
        mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        d.CmdPipelineBarrier(cmd,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            0, 1, &mb, 0, nullptr, 0, nullptr);
    }

    // ── 2. Coarse-to-fine motion estimation (top level → bottom) ────────────
    for (int lvl = (int)PYRAMID_LEVELS - 1; lvl >= 0; lvl--) {
        ImageBarrier(cmd, m_mvPyramid[lvl].image,
                     VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL,
                     0, VK_ACCESS_SHADER_WRITE_BIT,
                     VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                     VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);

        d.CmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_mvPipeline);

        MotionVectorPushConst pc = {
            m_prevPyramid[lvl].width,
            m_prevPyramid[lvl].height,
            (uint32_t)lvl,
            t
        };
        d.CmdPushConstants(cmd, m_mvPipeLayout,
                           VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(pc), &pc);

        uint32_t gx = (m_prevPyramid[lvl].width  + 7) / 8;
        uint32_t gy = (m_prevPyramid[lvl].height + 7) / 8;
        d.CmdDispatch(cmd, gx, gy, 1);

        VkMemoryBarrier mb = { VK_STRUCTURE_TYPE_MEMORY_BARRIER };
        mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        d.CmdPipelineBarrier(cmd,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            0, 1, &mb, 0, nullptr, 0, nullptr);
    }

    // Transition final mv image for external use
    ImageBarrier(cmd, mvImage,
                 VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                 VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT,
                 VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                 VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);
    (void)mvView;
}

// ─── SynthesizeFrame ─────────────────────────────────────────────────────────
void OpticalFlowEngine::SynthesizeFrame(
        VkCommandBuffer cmd,
        VkImageView     prevFrame,
        VkImageView     currFrame,
        VkImageView     mvView,
        VkImage         dstImage,
        VkImageView     dstView,
        float           t,
        bool            useUiMask,
        bool            stereoAware)
{
    const DeviceDispatch& d = m_ctx->dispatch;

    // ── Optional UI mask ─────────────────────────────────────────────────────
    if (useUiMask) {
        ImageBarrier(cmd, m_uiMaskImage,
                     VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL,
                     0, VK_ACCESS_SHADER_WRITE_BIT,
                     VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                     VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);

        d.CmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_maskPipeline);
        BlendPushConst pc = { m_width, m_height, t, 1 };
        d.CmdPushConstants(cmd, m_maskPipeLayout,
                           VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(pc), &pc);
        d.CmdDispatch(cmd, (m_width+7)/8, (m_height+7)/8, 1);

        VkMemoryBarrier mb = { VK_STRUCTURE_TYPE_MEMORY_BARRIER };
        mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        d.CmdPipelineBarrier(cmd,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            0, 1, &mb, 0, nullptr, 0, nullptr);
    }

    // ── Warp pass ─────────────────────────────────────────────────────────────
    ImageBarrier(cmd, dstImage,
                 VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL,
                 0, VK_ACCESS_SHADER_WRITE_BIT,
                 VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                 VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);

    d.CmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_warpPipeline);
    WarpPushConst wpc = { m_width, m_height, t, stereoAware ? 1u : 0u };
    d.CmdPushConstants(cmd, m_warpPipeLayout,
                       VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(wpc), &wpc);
    d.CmdDispatch(cmd, (m_width+7)/8, (m_height+7)/8, 1);

    {
        VkMemoryBarrier mb = { VK_STRUCTURE_TYPE_MEMORY_BARRIER };
        mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        d.CmdPipelineBarrier(cmd,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            0, 1, &mb, 0, nullptr, 0, nullptr);
    }

    // ── Blend pass ───────────────────────────────────────────────────────────
    d.CmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, m_blendPipeline);
    BlendPushConst bpc = { m_width, m_height, t, useUiMask ? 1u : 0u };
    d.CmdPushConstants(cmd, m_blendPipeLayout,
                       VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(bpc), &bpc);
    d.CmdDispatch(cmd, (m_width+7)/8, (m_height+7)/8, 1);

    // Transition output to shader-readable for present blit
    ImageBarrier(cmd, dstImage,
                 VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                 VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT,
                 VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                 VK_PIPELINE_STAGE_TRANSFER_BIT);

    (void)prevFrame; (void)currFrame; (void)mvView; (void)dstView;
}

// ─── Destroy ─────────────────────────────────────────────────────────────────
void OpticalFlowEngine::Destroy() {
    if (!m_ctx) return;
    VkDevice dev = m_ctx->device;
    const DeviceDispatch& d = m_ctx->dispatch;

    d.DeviceWaitIdle(dev);

    for (auto& lvl : m_prevPyramid) FreePyramidLevel(lvl);
    for (auto& lvl : m_currPyramid) FreePyramidLevel(lvl);
    for (auto& lvl : m_mvPyramid)   FreePyramidLevel(lvl);

    if (m_uiMaskView)   d.DestroyImageView(dev, m_uiMaskView, nullptr);
    if (m_uiMaskImage)  d.DestroyImage(dev, m_uiMaskImage, nullptr);
    if (m_uiMaskMem)    d.FreeMemory(dev, m_uiMaskMem, nullptr);

    if (m_linearSampler)  d.DestroySampler(dev, m_linearSampler, nullptr);
    if (m_nearestSampler) d.DestroySampler(dev, m_nearestSampler, nullptr);

    // Destroy pipelines
    auto destroyPipe = [&](VkPipeline& p, VkPipelineLayout& l) {
        if (p) { d.DestroyPipeline(dev, p, nullptr); p = VK_NULL_HANDLE; }
        if (l) { d.DestroyPipelineLayout(dev, l, nullptr); l = VK_NULL_HANDLE; }
    };
    destroyPipe(m_pyramidPipeline, m_pyramidPipeLayout);
    destroyPipe(m_mvPipeline,      m_mvPipeLayout);
    destroyPipe(m_warpPipeline,    m_warpPipeLayout);
    destroyPipe(m_blendPipeline,   m_blendPipeLayout);
    destroyPipe(m_maskPipeline,    m_maskPipeLayout);

    // Destroy descriptor layouts
    auto destroyLayout = [&](VkDescriptorSetLayout& l) {
        if (l) { d.DestroyDescriptorSetLayout(dev, l, nullptr); l = VK_NULL_HANDLE; }
    };
    destroyLayout(m_pyramidLayout);
    destroyLayout(m_mvLayout);
    destroyLayout(m_warpLayout);
    destroyLayout(m_blendLayout);
    destroyLayout(m_maskLayout);

    if (m_descPool) d.DestroyDescriptorPool(dev, m_descPool, nullptr);

    m_ctx = nullptr;
}
