# ─── cmake/SpvToHeader.cmake ─────────────────────────────────────────────────
# Converts a .spv binary into a C++ header with a uint32_t[] array.
# Called automatically by CMakeLists.txt for each shader.
#
# Variables expected:
#   INPUT     — path to .spv file
#   OUTPUT    — path to output .h file
#   VAR_NAME  — name of the C array variable

cmake_minimum_required(VERSION 3.10)

file(READ "${INPUT}" SPV_HEX HEX)

# Split into 4-byte (8 hex char) chunks
string(LENGTH "${SPV_HEX}" SPV_HEX_LEN)
math(EXPR NUM_WORDS "${SPV_HEX_LEN} / 8")

set(ARRAY_BODY "")
math(EXPR LAST_WORD "${NUM_WORDS} - 1")
foreach(i RANGE ${LAST_WORD})
    math(EXPR OFFSET "${i} * 8")
    string(SUBSTRING "${SPV_HEX}" ${OFFSET} 8 CHUNK)
    # Reverse byte order (little-endian)
    string(SUBSTRING "${CHUNK}" 6 2 B0)
    string(SUBSTRING "${CHUNK}" 4 2 B1)
    string(SUBSTRING "${CHUNK}" 2 2 B2)
    string(SUBSTRING "${CHUNK}" 0 2 B3)
    set(WORD "0x${B0}${B1}${B2}${B3}")
    if(i LESS LAST_WORD)
        string(APPEND ARRAY_BODY "    ${WORD},\n")
    else()
        string(APPEND ARRAY_BODY "    ${WORD}\n")
    endif()
endforeach()

math(EXPR SPV_BYTES "${SPV_HEX_LEN} / 2")

set(HEADER_CONTENT
"// Auto-generated by SpvToHeader.cmake — DO NOT EDIT
// Source: ${INPUT}
#pragma once
#include <stdint.h>
static const uint32_t ${VAR_NAME}[] = {
${ARRAY_BODY}};
static const size_t ${VAR_NAME}_size = ${SPV_BYTES};
")

file(WRITE "${OUTPUT}" "${HEADER_CONTENT}")
message(STATUS "SpvToHeader: wrote ${OUTPUT} (${SPV_BYTES} bytes, ${NUM_WORDS} words)")
